version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./application/:/var/www
    environment:
      - "DB_PORT=3306"
      - "host=192.168.99.100"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    links:
      - app
    ports:
      - 8000:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=pln_monitoring"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=mainan123"
      - "MYSQL_ROOT_PASSWORD=mainan123"
    ports:
        - "33060:3306"

volumes:
  db:
